version: '3'
services:
  game:
    container_name: lingleGame
    build: 
      context: ./ui
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    links:
      - "server"
    networks: 
      - linglenet
    command: npm run dev
    

  server:
    container_name: lingleAPI
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - elasticsearch
    ports:
      - "8080:8080"
    command: npm run start
    networks: 
      - linglenet

  
  elasticsearch:
    container_name: es_db
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - discovery.type=single-node
    networks:
      - linglenet
networks:
  linglenet: