version: '3'
services:
  game:
    container_name: lingleGame
    build: 
      context: ./ui
      dockerfile: ./Dockerfile
    links:
      - "server"
    networks: 
      - linglenet
    command: npm run serve
    
  server:
    container_name: lingleAPI
    build: 
      context: ./api
      dockerfile: ./Dockerfile
    depends_on:
      - elasticsearch
    command: npm run start
    networks: 
      - linglenet

  reverseproxy:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    depends_on:
      - game
      - server
    networks:
      - linglenet
    ports:
      - "80:80"
      - "443:443"
    volumes: 
     - /Users/hashmibilal/Desktop/certs:/etc/nginx/certs

  elasticsearch:
    container_name: es_db
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
    networks:
      - linglenet
networks:
  linglenet: